### PR TITLE
Questions you came up with after the course is over

### PR DESCRIPTION
**Pull request by nlaugel**
## What does this Pull Request do?
Add a markdown file for people who couldn't think of anything funny on the day to submit as a pull request, got back to it later to finish the assignment, and figure they have non-joke questions they might have asked Gerard.
The contents might be useful to them, to formulate questions, to Gerard, to offer topics to bring up if his next batch of students can't come up with their own questions, or to the next batch of students themselves at the end of their course.

## Where should the reviewer start?
Check out next_day_questions.md

## Any context I need to know about?
No

## Does this fix any issues?
No

### CODE REVIEW

**Comment by nlaugel** [comment]
Thank you for the course Gerard :thumbsup:

**Comment by gcapes** [comment]
This is an excellent idea, thanks! I'll try to find some time to answer your questions over the next couple of weeks.

**Comment by gcapes** [comment]
Apologies for the huge delay. I'm not quite sure of the best place for this, but we'll leave it here for now. I'll merge this and then add some answers to the file.

**Comment by gcapes** [comment]
Ok, I've just added some thoughts to answer those questions @nlaugel https://github.com/gcapes/manchester-papers/blob/master/next_day_questions.md

**Pull request merged**
